[colors.primary]
background = "#0c0c0c"
foreground = "#d0d0d0"

[colors.cursor]
text = "#0c0c0c"
cursor = "#b8b8b8"

[colors.selection]
text = "#e0e0e0"
background = "#292929"

[colors.normal]
black = "#171717"
red = "#c96b6b"
green = "#86a878"
yellow = "#c0a76b"
blue = "#7189a8"
magenta = "#9b7fa3"
cyan = "#719b9a"
white = "#c7c7c7"

[colors.bright]
black = "#303030"
red = "#df8080"
green = "#a2c293"
yellow = "#d5bd7e"
blue = "#8da7c7"
magenta = "#b495bc"
cyan = "#8bbdbc"
white = "#eeeeee"

